// Define an array of word objects
const words = [
    { word: "행복", definition: "Happiness / Glück", example: "Ich wünsche Ihnen viel Glück!", examplekr: "행운을 빌어요!" },
    { word: "사랑", definition: "Love / Liebe", example: "Ich liebe dich <3", examplekr: "사랑해요 <3" },
    { word: "꽃", definition: "Flower / Blume", example: "Blumen wachsen natürlich aus der Erde", examplekr: "꽃은 땅에서 자연적으로 자라납니다." },
    { word: "행복", definition: "Glück", examplekr: "그가 행복하다.", example: "Er ist glücklich." },
    { word: "가족", definition: "Familie", examplekr: "우리 가족은 행복해요.", example: "Unsere Familie ist glücklich." },
    { word: "친구", definition: "Freund", examplekr: "나는 그의 친구에요.", example: "Ich bin sein Freund." },
    { word: "학교", definition: "Schule", examplekr: "내일 학교에 가요.", example: "Ich gehe morgen zur Schule." },
    { word: "음식", definition: "Essen", examplekr: "이 음식은 맛있어요.", example: "Dieses Essen ist lecker." },
    { word: "여행", definition: "Reise", examplekr: "여행을 가고 싶어요.", example: "Ich möchte verreisen." },
    { word: "공부", definition: "Studium", examplekr: "나는 매일 공부해요.", example: "Ich studiere jeden Tag." },
    { word: "영화", definition: "Film", examplekr: "이 영화는 재미있어요.", example: "Dieser Film ist unterhaltsam." },
    { word: "음악", definition: "Musik", examplekr: "나는 음악을 좋아해요.", example: "Ich mag Musik." },
    { word: "시간", definition: "Zeit", examplekr: "나는 시간이 없어요.", example: "Ich habe keine Zeit." },
    { word: "돈", definition: "Geld", examplekr: "돈이 필요해요.", example: "Ich brauche Geld." },
    { word: "운동", definition: "Sport", examplekr: "나는 운동을 좋아해요.", example: "Ich mag Sport." },
    { word: "책", definition: "Buch", examplekr: "이 책은 재미있어요.", example: "Dieses Buch ist interessant." },
    { word: "집", definition: "Haus", examplekr: "우리 집은 크다.", example: "Unser Haus ist groß." },
    { word: "날씨", definition: "Wetter", examplekr: "오늘 날씨가 좋아요.", example: "Das Wetter ist schön heute." },
    { word: "사진", definition: "Foto", examplekr: "이 사진은 아름답다.", example: "Dieses Foto ist schön." },
    { word: "꽃", definition: "Blume", examplekr: "이 꽃은 예쁘다.", example: "Diese Blume ist schön." },
    { word: "모자", definition: "Hut", examplekr: "그 모자는 이쁘다.", example: "Dieser Hut ist hübsch." },
    { word: "컴퓨터", definition: "Computer", examplekr: "나는 컴퓨터를 사용해요.", example: "Ich benutze den Computer." },
    { word: "바다", definition: "Meer", examplekr: "바다가 아름답다.", example: "Das Meer ist schön." },
    { word: "산", definition: "Berg", examplekr: "저는 산을 좋아해요.", example: "Ich mag Berge." },
    { word: "강아지", definition: "Hund", examplekr: "우리 강아지는 귀엽다.", example: "Unser Hund ist süß." },
    { word: "고양이", definition: "Katze", examplekr: "그 고양이는 귀엽다.", example: "Diese Katze ist süß." },
    { word: "새", definition: "Vogel", examplekr: "그 새는 날 수 있다.", example: "Dieser Vogel kann fliegen." },
    { word: "커피", definition: "Kaffee", examplekr: "커피를 마시고 싶어요.", example: "Ich möchte Kaffee trinken." },
    { word: "차", definition: "Auto", examplekr: "저는 차를 가지고 있어요.", example: "Ich habe ein Auto." },
    { word: "의사", definition: "Arzt", examplekr: "나는 의사가 되고 싶어요.", example: "Ich möchte Arzt werden." },
    { word: "핸드폰", definition: "Handy", examplekr: "나는 핸드폰을 잃어버렸어요.", example: "Ich habe mein Handy verloren." },
    { word: "사과", definition: "Apfel", examplekr: "사과를 좋아해요.", example: "Ich mag Äpfel." },
    { word: "물", definition: "Wasser", examplekr: "물을 마셔야 돼요.", example: "Man muss Wasser trinken." },
    { word: "어머니", definition: "Mutter", examplekr: "어머니가 맛있는 음식을 만들어요.", example: "Meine Mutter kocht leckeres Essen." },
    { word: "아버지", definition: "Vater", examplekr: "아버지가 일하고 계세요.", example: "Mein Vater arbeitet gerade." },
    { word: "형제", definition: "Geschwister", examplekr: "저는 두 형제가 있어요.", example: "Ich habe zwei Geschwister." },
    { word: "자동차", definition: "Auto", examplekr: "나는 자동차를 타요.", example: "Ich fahre Auto." },
    { word: "우산", definition: "Regenschirm", examplekr: "비가 오니까 우산을 가져가세요.", example: "Nimm einen Regenschirm, es regnet." },
    { word: "카메라", definition: "Kamera", examplekr: "카메라로 사진을 찍어요.", example: "Ich mache Fotos mit der Kamera." },
    { word: "휴대폰", definition: "Handy", examplekr: "휴대폰을 잃어버렸어요.", example: "Ich habe mein Handy verloren." },
    { word: "텔레비전", definition: "Fernseher", examplekr: "텔레비전을 봐요.", example: "Ich sehe fern." },
    { word: "시계", definition: "Uhr", examplekr: "시계가 필요해요.", example: "Ich brauche eine Uhr." },
    { word: "가방", definition: "Tasche", examplekr: "가방을 가져가세요.", example: "Nimm die Tasche mit." },
    { word: "책상", definition: "Schreibtisch", examplekr: "책상 위에 책이 있어요.", example: "Auf dem Schreibtisch liegen Bücher." },
    { word: "의자", definition: "Stuhl", examplekr: "의자에 앉아요.", example: "Ich setze mich auf den Stuhl." },
    { word: "컵", definition: "Tasse", examplekr: "컵에 차를 마셔요.", example: "Ich trinke Tee aus der Tasse." },
    { word: "신발", definition: "Schuhe", examplekr: "신발을 신고 나가요.", example: "Ich ziehe Schuhe an und gehe raus." },
    { word: "가게", definition: "Geschäft", examplekr: "가게에서 물건을 샀어요.", example: "Ich habe im Geschäft etwas gekauft." },
    { word: "길", definition: "Straße", examplekr: "길을 걸어요.", example: "Ich gehe auf der Straße." },
    { word: "공원", definition: "Park", examplekr: "공원에서 산책해요.", example: "Ich mache einen Spaziergang im Park." },
    { word: "꿈", definition: "Traum", examplekr: "나는 꿈이 있어요.", example: "Ich habe einen Traum." },
    { word: "눈", definition: "Schnee", examplekr: "눈이 와요.", example: "Es schneit." },
    { word: "물고기", definition: "Fisch", examplekr: "물고기를 잡아 먹어요.", example: "Ich fange Fische und esse sie." },
    { word: "모자이크", definition: "Mosaik", examplekr: "모자이크가 아름다워요.", example: "Das Mosaik ist schön." },
    { word: "교회", definition: "Kirche", examplekr: "교회에 가세요.", example: "Geh zur Kirche." },
    { word: "아파트", definition: "Wohnung", examplekr: "아파트에 살아요.", example: "Ich wohne in einer Wohnung." },
    { word: "밥", definition: "Reis", examplekr: "밥을 먹어요.", example: "Ich esse Reis." },
    { word: "선물", definition: "Geschenk", examplekr: "선물을 주세요.", example: "Gib mir ein Geschenk." },
    { word: "공항", definition: "Flughafen", examplekr: "공항에 가요.", example: "Ich gehe zum Flughafen." },
    { word: "식당", definition: "Restaurant", examplekr: "식당에서 밥을 먹어요.", example: "Ich esse im Restaurant." },
    { word: "쇼핑", definition: "Shopping", examplekr: "쇼핑하러 가요.", example: "Ich gehe einkaufen." },
    { word: "자전거", definition: "Fahrrad", examplekr: "자전거를 타요.", example: "Ich fahre Fahrrad." },
    { word: "버스", definition: "Bus", examplekr: "버스를 타요.", example: "Ich fahre Bus." },
    { word: "지하철", definition: "U-Bahn", examplekr: "지하철을 타요.", example: "Ich fahre U-Bahn." },
    { word: "비행기", definition: "Flugzeug", examplekr: "비행기를 타요.", example: "Ich fliege mit dem Flugzeug." },
    { word: "택시", definition: "Taxi", examplekr: "택시를 타요.", example: "Ich nehme ein Taxi." },
    { word: "책임", definition: "Verantwortung", examplekr: "나는 책임이 있어요.", example: "Ich bin verantwortlich." },
    { word: "모임", definition: "Treffen", examplekr: "우리는 모임을 가요.", example: "Wir gehen zu einem Treffen." },
    { word: "불행", definition: "Unglück", examplekr: "그는 불행해요.", example: "Er ist unglücklich." },
    { word: "행동", definition: "Handlung", examplekr: "그의 행동은 이상해요.", example: "Sein Verhalten ist seltsam." },
    { word: "꿈", definition: "Traum", examplekr: "나는 꿈을 꾸고 있어요.", example: "Ich träume." },
    { word: "숙제", definition: "Hausaufgaben", examplekr: "나는 숙제를 해요.", example: "Ich mache meine Hausaufgaben." },
    { word: "시간표", definition: "Zeitplan", examplekr: "나는 시간표를 만들었어요.", example: "Ich habe einen Zeitplan erstellt." },
    { word: "숙소", definition: "Unterkunft", examplekr: "우리는 숙소에 있어요.", example: "Wir sind in einer Unterkunft." },
    { word: "후회", definition: "Bedauern", examplekr: "나는 후회해요.", example: "Ich bereue es." },
    { word: "전화", definition: "Anruf", examplekr: "나는 전화를 받아요.", example: "Ich nehme den Anruf an." },
    { word: "가격", definition: "Preis", examplekr: "이것의 가격이 얼마에요?", example: "Wie viel kostet das?" },
    { word: "도움", definition: "Hilfe", examplekr: "도움을 받아요.", example: "Ich erhalte Hilfe." },
    { word: "경험", definition: "Erfahrung", examplekr: "그것은 좋은 경험이에요.", example: "Es ist eine gute Erfahrung." },
    { word: "도착", definition: "Ankunft", examplekr: "우리는 도착했어요.", example: "Wir sind angekommen." },
    { word: "출발", definition: "Abfahrt", examplekr: "우리는 출발해요.", example: "Wir fahren ab." },
    { word: "미래", definition: "Zukunft", examplekr: "미래는 밝아요.", example: "Die Zukunft ist hell." },
    { word: "과거", definition: "Vergangenheit", examplekr: "과거는 지나갔어요.", example: "Die Vergangenheit ist vorbei." },
    { word: "계획", definition: "Plan", examplekr: "계획을 세워요.", example: "Ich mache Pläne." },
    { word: "문제", definition: "Problem", examplekr: "문제가 있어요.", example: "Es gibt ein Problem." },
    { word: "의문", definition: "Frage", examplekr: "의문이 있어요.", example: "Ich habe eine Frage." },
    { word: "정답", definition: "Antwort", examplekr: "정답이 뭐에요?", example: "Was ist die Antwort?" },
    { word: "목표", definition: "Ziel", examplekr: "나는 목표를 가지고 있어요.", example: "Ich habe ein Ziel." },
    { word: "연습", definition: "Übung", examplekr: "나는 연습을 해요.", example: "Ich übe." },
    { word: "결정", definition: "Entscheidung", examplekr: "나는 결정을 내려요.", example: "Ich treffe eine Entscheidung." },
    { word: "희망", definition: "Hoffnung", examplekr: "나는 희망을 가지고 있어요.", example: "Ich habe Hoffnung." },
    { word: "소원", definition: "Wunsch", examplekr: "나의 소원은 무엇인가요?", example: "Was ist dein Wunsch?" },
    { word: "약속", definition: "Versprechen", examplekr: "우리는 약속을 해요.", example: "Wir machen ein Versprechen." },
    { word: "전투", definition: "Kampf", examplekr: "우리는 전투를 벌여요.", example: "Wir kämpfen." },
    { word: "평화", definition: "Frieden", examplekr: "나는 평화를 원해요.", example: "Ich wünsche mir Frieden." },
    { word: "사망", definition: "Tod", examplekr: "그녀는 사망했어요.", example: "Sie ist gestorben." },
    { word: "걱정", definition: "Sorge", examplekr: "나는 걱정해요.", example: "Ich mache mir Sorgen." },
    { word: "겁", definition: "Angst", examplekr: "나는 겁이 있어요.", example: "Ich habe Angst." },
    { word: "낙관", definition: "Optimismus", examplekr: "나는 낙관적이에요.", example: "Ich bin optimistisch." },
    { word: "비난", definition: "Kritik", examplekr: "그는 비난을 받았어요.", example: "Er wurde kritisiert." },
    { word: "자부심", definition: "Stolz", examplekr: "나는 자부심을 느껴요.", example: "Ich bin stolz." }
];

// Function to display a random word
function displayRandomWord() {
    // Generate a random index within the range of the words array length
    const randomIndex = Math.floor(Math.random() * words.length);
    const randomWord = words[randomIndex];

    // Update the content of the elements with the random word's information
    document.getElementById("word").textContent = randomWord.word;
    document.getElementById("definition").textContent = "Bedeutung: " + randomWord.definition;
    document.getElementById("example").textContent = "Beispiel: " + randomWord.example;
    document.getElementById("examplekr").textContent = randomWord.examplekr;
}

// Add event listener to the "New Word" button
document.getElementById("newWordBtn").addEventListener("click", displayRandomWord);

// Display a random word when the page loads
displayRandomWord();
